Repository starkware-libs/starkgate-frontend, pull requests merged in 2022-03, with the labels that each got.

#89 fix: redux error on switching menu "non-serializable value was detected"
  src/components/Features/Account/Account.js
  src/components/Features/SelectToken/SelectToken.js
Labels: READY FOR REVIEW

#92 fix: remove pending transfer toast
  src/components/Features/ToastProvider/ToastProvider.js
Labels: READY FOR REVIEW

#97 feat: responsiveness
  package.json
  src/components/Containers/Footer/Footer.js
  src/components/Containers/Header/Header.js
  src/components/Containers/Header/Header.module.scss
  src/components/Features/ToastProvider/ToastProvider.js
  src/components/UI/Button/Button.js
  src/components/UI/WalletButton/WalletButton.constants.js
  src/components/UI/WalletButton/WalletButton.js
  src/components/UI/WalletButton/WalletButton.module.scss
  src/enums/Breakpoint.js
  src/enums/index.js
  yarn.lock
Labels: in progress

#104 feat: add discord tab
  src/components/Containers/Header/Header.js
  src/components/Containers/Header/Header.module.scss
  src/components/Containers/Header/Header.strings.js
  src/components/UI/Tab/Tab.js
  src/components/UI/Tab/Tab.module.scss
  src/components/UI/WalletButton/WalletButton.module.scss
  src/components/UI/index.js
  src/config/constants.js
  src/config/strings.js
  src/utils/browser.js
Labels: ready for review

#106 feat: FAQ tab
  src/components/Containers/Header/Header.js
  src/components/Containers/Header/Header.module.scss
  src/components/Containers/Header/Header.strings.js
  src/components/Features/Bridge/Bridge.js
  src/components/Features/FAQ/FAQ.js
  src/components/Features/FAQ/FAQ.module.scss
  src/components/Features/FAQ/FAQ.strings.js
  src/components/Features/index.js
  src/components/UI/Tab/Tab.js
  src/components/UI/Tab/Tab.module.scss
  src/components/UI/WalletButton/WalletButton.module.scss
  src/config/faqs.js
  src/config/strings.js
  src/enums/MenuType.js
  src/providers/MenuProvider/menu-hooks.js
Labels: ready for review

#99 chore(semantic-release): continuous integration
  .eslintrc.json
  .github/workflows/push.yml
  CHANGELOG.md
  package.json
  release.config.js
  src/components/Features/Bridge/Bridge.js
  yarn.lock
Labels: in progress

#103 chore: continuous deployment
  .github/workflows/gcr_push_workflow.yml
  .github/workflows/push_backend_images.yml
  .github/workflows/push_frontend_images.yml
  .github/workflows/tag.yml
  DOCKER.md
  Dockerfile.frontend
  deployment/README.md
  deployment/development.yml
  deployment/production.yml
  deployment/testing.yml
  package.json
Labels: in progress

#109 feat: onboarding modal
  .env.development
  .env.production
  src/__tests__/utils/date.spec.js
  src/components/Features/Bridge/Bridge.js
  src/components/UI/Modal/OnboardingModal/OnboardingModal.js
  src/components/UI/Modal/OnboardingModal/OnboardingModal.module.scss
  src/components/UI/Modal/OnboardingModal/OnboardingModal.strings.js
  src/config/envs.js
  src/config/strings.js
  src/providers/ModalProvider/modal-hooks.js
  src/utils/date.js
  yarn.lock
Labels: ready for review

#81 chore: update packages
  .github/workflows/pull_request.yml
  deployment/development.yml
  deployment/production.yml
  deployment/testing.yml
  package.json
  src/api/erc20.js
  src/providers/EventManagerProvider/EventManagerProvider.js
  src/providers/WalletsProvider/WalletsProvider.js
  src/utils/blockchain/starknet.js
  src/wallets/argent-x.js
  yarn.lock
Labels: in progress
